# These are supported funding model platforms

github: [aidan846]
ko_fi: aj006
buy_me_a_coffee: aj06
custom: ['https://www.paypal.com/donate/?business=WK6MSSHYNPCHS&no_recurring=0&currency_code=USD']
